<?php

define( 'API_KEY','aDGMjCDgqnLAR7qkt-0_FV2lRYYTzmbPcI4EYg9FRvOfLaZlB9dtcO-tCCeBza9NM0ShudP6iY7RdsYlXxK9z4wxO9fvAwULN9L97pIS0l3VJD8u8EB-MeBTVqSkWnYx');
// define( 'API_SECRET','AOgxWuCGtNalU0SwICXu8VEFpbESZslvZFY3hEJRx0xntoAbYPLTReAVYVQfRNYK' );
